title: "My Tech Blog"
description: "Insights on engineering practices and management."
url: "https://gagapov.github.io"
baseurl: "/blog"
exclude:
  - node_modules
  - vendor
  - conductor
  - Gemfile
  - Gemfile.lock
