title: "Gerald writes"
description: "Insights on engineering practices and management."
url: "https://geraldagapov.github.io"
baseurl: "/blog"
exclude:
  - node_modules
  - vendor
  - conductor
  - Gemfile
  - Gemfile.lock
